version = 1

[[annotations]]
path = ["src/**", "notebooks/*.py", "notebooks/*.ipynb", "notebooks/*.rb", "data/download_from_server.rb"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = ["README.md", "data/stops/**/README.md", ".github/*.png", "output/**/isochrones*", "data/crs.yaml", "data/stops/**/stops_test.csv"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["data/stops/**/stops_with_centrality.csv", "data/stops/**/accessible_stops.json", "data/stops/**/*.pkl", "data/stops/**/*.pkl.gz"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Máté Mizsák"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["data/osm/**/boundary*.geojson", "data/geojson/*"]
precedence = "override"
SPDX-FileCopyrightText = "OpenStreetMap contributors"
SPDX-License-Identifier = "ODbL-1.0"

[[annotations]]
path = ["data/statistics/finland/*", "data/statistics/helsinki/**/*"]
precedence = "override"
SPDX-FileCopyrightText = "Statistics Finland"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["data/statistics/spain/*", "data/statistics/madrid/*"]
precedence = "override"
SPDX-FileCopyrightText = "Instituto Nacional de Estadística"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["**/.gitignore", "CITATION.cff", "plotting_config.yaml", "pyproject.toml", "poetry.lock", ".python-version"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "0BSD"
